# Generated by Django 4.2.14 on 2026-08-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnqueteMobilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commune', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=100)),
                ('mode_transport_actuel', models.CharField(max_length=100)),
                ('temps_deplacement', models.CharField(max_length=100)),
                ('moment_arrivee', models.CharField(max_length=100)),
                ('moment_depart', models.CharField(max_length=100)),
                ('combinaison_transport', models.CharField(max_length=10)),
                ('itineraire_combinaison', models.CharField(blank=True, max_length=255, null=True)),
                ('problemes_deplacement', models.CharField(max_length=255)),
                ('situation_dangereuse', models.CharField(max_length=10)),
                ('precision_situation_dangereuse', models.TextField(blank=True, null=True)),
                ('evaluation_organisation_deplacements', models.CharField(max_length=100)),
                ('amenagements_souhaites', models.JSONField(default=list)),
                ('avantage_pole_echange', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Réponse à l'enquête",
                'verbose_name_plural': "Réponses à l'enquête",
                'ordering': ['-date_creation'],
            },
        ),
    ]
