# Generated by Django 4.2.14 on 2026-08-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquetemobilite',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='enquetemobilite',
            name='quartier',
        ),
        migrations.AddField(
            model_name='enquetemobilite',
            name='residence',
            field=models.JSONField(default=list),
        ),
    ]
